# Generated by Django 5.0.1 on 2024-01-10 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=255, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=8, verbose_name='Telephone')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('age', models.PositiveIntegerField(blank=True, default=0, verbose_name='age')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('personnel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.personnel')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('market.personnel',),
        ),
        migrations.CreateModel(
            name='Caissier',
            fields=[
                ('personnel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.personnel')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caissier', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('market.personnel',),
        ),
        migrations.CreateModel(
            name='Gerant',
            fields=[
                ('personnel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.personnel')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerant', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('market.personnel',),
        ),
    ]
