# Generated by Django 5.0.1 on 2024-01-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_approvisionnnement_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='quantite'),
        ),
    ]
