# Generated by Django 5.0.1 on 2024-01-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_produit_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(default=None, max_length=255, verbose_name='Code client'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='designation',
            field=models.CharField(max_length=255, verbose_name='designation'),
        ),
    ]
