# Generated by Django 5.0.1 on 2024-01-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_client_code_alter_produit_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, default=None, editable=False, max_length=255, null=True, unique=True, verbose_name='Code client'),
        ),
    ]
