# Generated by Django 5.0.1 on 2024-01-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_client_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='date_debut',
            field=models.DateField(verbose_name='Date de debut de la promotion'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='date_fin',
            field=models.DateField(verbose_name='Date de debut de la promotion'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='quantite',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Quantite'),
        ),
    ]
