# Generated by Django 5.0.1 on 2024-01-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_promotion_date_debut_alter_promotion_date_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date de vente'),
        ),
    ]
