# Generated by Django 5.0.1 on 2024-01-18 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_vente_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vente',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', to='market.client', verbose_name='Client'),
        ),
    ]
