# Generated by Django 5.0.1 on 2024-01-19 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_vente_options_alter_vente_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='market.produit', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantite'),
        ),
    ]
