# Generated by Django 5.0.1 on 2024-01-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_vente_produit_alter_vente_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='pourcentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pourcentage de reductions'),
        ),
    ]
