# Generated by Django 5.0.1 on 2024-01-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_alter_promotion_pourcentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vente',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='vente',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de vente'),
        ),
    ]
