# Generated by Django 5.0.1 on 2024-01-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_alter_vente_options_alter_vente_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vente',
            options={'ordering': ['-date']},
        ),
    ]
