# Generated by Django 5.0.1 on 2024-01-19 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_vente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='pourcentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.01)], verbose_name='Pourcentage de reductions'),
        ),
    ]
