# Generated by Django 5.0.1 on 2024-01-19 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_alter_promotion_pourcentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='pourcentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100.0, message='Le pourcentage doit être inférieur ou égal à 100.'), django.core.validators.MinValueValidator(0.01, message='Le pourcentage doit être supérieur ou égal à 0.01.')], verbose_name='Pourcentage de reductions'),
        ),
    ]
