# Generated by Django 5.0.1 on 2024-01-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_alter_promotion_pourcentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=8, unique=True, verbose_name='Telephone'),
        ),
    ]
