# Generated by Django 5.0.1 on 2024-01-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_alter_client_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='alerte_rupture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=255, verbose_name='contenu')),
                ('etat', models.BooleanField(default=False, verbose_name='etat')),
            ],
        ),
        migrations.RemoveField(
            model_name='approvisionnnement',
            name='date',
        ),
        migrations.AddField(
            model_name='approvisionnnement',
            name='date_confirmation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de confirmation de l'approvisionnement"),
        ),
        migrations.AddField(
            model_name='approvisionnnement',
            name='date_demande',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name="Date de demande d'approvisionnement"),
        ),
    ]
