# Generated by Django 5.0.1 on 2024-01-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_alerte_rupture_remove_approvisionnnement_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Approvisionnnement',
            new_name='Approvisionnement',
        ),
    ]
