# Generated by Django 5.0.1 on 2024-01-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_alter_approvisionnement_date_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnement',
            name='etat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
