# Generated by Django 5.0.1 on 2024-01-20 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_approvisionnement_etat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alerte_rupture',
            new_name='AlerteRupture',
        ),
    ]
